export interface TarotCard {
  id: number;
  name: string;
  arcana: "Major" | "Minor";
  meaningUpright: string;
  meaningReversed: string;
  image: string;
}

export interface DrawnCard extends TarotCard {
  isReversed: boolean;
}

export const tarotCards: TarotCard[] = [
  // === BÜYÜK ARKANA (MAJOR ARCANA) - 22 KART ===
  {
    id: 0,
    name: "The Fool (Deli / Mecnun)",
    arcana: "Major",
    meaningUpright: "Yeni başlangıçlar, masumiyet, macera, özgür ruh.",
    meaningReversed: "Dikkatsizlik, ihmalkarlık, aptalca riskler, hazırlıksızlık.",
    image: "/images/cards/fool.jpg",
  },
  {
    id: 1,
    name: "The Magician (Büyücü)",
    arcana: "Major",
    meaningUpright: "Yetenek, irade, odaklanma, tezahür ettirme gücü.",
    meaningReversed: "Manipülasyon, kullanılmayan potansiyel, kötüye kullanım.",
    image: "/images/cards/magician.jpg",
  },
  {
    id: 2,
    name: "The High Priestess (Azize)",
    arcana: "Major",
    meaningUpright: "Sezgi, bilinçaltı, gizem, içsel bilgi.",
    meaningReversed: "Sırlar, yüzeysellik, sezgileri görmezden gelme.",
    image: "/images/cards/high-priestess.jpg",
  },
  {
    id: 3,
    name: "The Empress (İmparatoriçe)",
    arcana: "Major",
    meaningUpright: "Bolluk, bereket, doğurganlık, annelik, doğa.",
    meaningReversed: "Yaratıcılık tıkanıklığı, bağımlılık, bereketsizlik.",
    image: "/images/cards/empress.jpg",
  },
  {
    id: 4,
    name: "The Emperor (İmparator)",
    arcana: "Major",
    meaningUpright: "Otorite, yapı, kontrol, babalık, liderlik.",
    meaningReversed: "Tiranlık, esneklik eksikliği, güç suistimali.",
    image: "/images/cards/emperor.jpg",
  },
  {
    id: 5,
    name: "The Hierophant (Aziz)",
    arcana: "Major",
    meaningUpright: "Gelenekler, inançlar, ruhani rehberlik, eğitim.",
    meaningReversed: "İsyan, yeni yaklaşımlar, tabuları yıkma.",
    image: "/images/cards/hierophant.jpg",
  },
  {
    id: 6,
    name: "The Lovers (Aşıklar)",
    arcana: "Major",
    meaningUpright: "Aşk, uyum, ilişkiler, değerlerin hizalanması, seçimler.",
    meaningReversed: "Uyumsuzluk, dengesizlik, yanlış kararlar.",
    image: "/images/cards/lovers.jpg",
  },
  {
    id: 7,
    name: "The Chariot (Araba)",
    arcana: "Major",
    meaningUpright: "Kontrol, irade gücü, başarı, azim, zafer.",
    meaningReversed: "Kontrol kaybı, yön eksikliği, saldırganlık.",
    image: "/images/cards/chariot.jpg",
  },
  {
    id: 8,
    name: "Strength (Güç)",
    arcana: "Major",
    meaningUpright: "Güç, cesaret, şefkat, yumuşak güç, sabır.",
    meaningReversed: "Kendine güvensizlik, zayıflık, çiğ öfke.",
    image: "/images/cards/strength.jpg",
  },
  {
    id: 9,
    name: "The Hermit (Ermiş)",
    arcana: "Major",
    meaningUpright: "İç gözlem, yalnızlık, içsel arayış, bilgelik.",
    meaningReversed: "Yalnızlaşma, asosyallik, gerçeklerden kaçma.",
    image: "/images/cards/hermit.jpg",
  },
  {
    id: 10,
    name: "Wheel of Fortune (Kader Çarkı)",
    arcana: "Major",
    meaningUpright: "Şans, kader, döngüler, büyük değişiklikler.",
    meaningReversed: "Kötü şans, direnç, kontrol dışı durumlar.",
    image: "/images/cards/wheel-of-fortune.jpg",
  },
  {
    id: 11,
    name: "Justice (Adalet)",
    arcana: "Major",
    meaningUpright: "Adalet, dürüstlük, gerçek, sebep-sonuç ilişkisi.",
    meaningReversed: "Adaletsizlik, dürüst olmama, hesap sorulamazlık.",
    image: "/images/cards/justice.jpg",
  },
  {
    id: 12,
    name: "The Hanged Man (Asılan Adam)",
    arcana: "Major",
    meaningUpright: "Duraklama, teslimiyet, yeni bakış açısı, fedakarlık.",
    meaningReversed: "Gecikme, kararsızlık, direnme, boşuna fedakarlık.",
    image: "/images/cards/hanged-man.jpg",
  },
  {
    id: 13,
    name: "Death (Ölüm)",
    arcana: "Major",
    meaningUpright: "Sonlanma, dönüşüm, geçiş, yeni başlangıçlar.",
    meaningReversed: "Değişime direnç, durgunluk, bırakamama.",
    image: "/images/cards/death.jpg",
  },
  {
    id: 14,
    name: "Temperance (Denge)",
    arcana: "Major",
    meaningUpright: "Denge, ılımlılık, sabır, amaç bulma.",
    meaningReversed: "Dengesizlik, aşırılık, uyumsuzluk.",
    image: "/images/cards/temperance.jpg",
  },
  {
    id: 15,
    name: "The Devil (Şeytan)",
    arcana: "Major",
    meaningUpright: "Gölge benlik, bağlanma, bağımlılık, kısıtlanma.",
    meaningReversed: "Serbest kalma, bağımsızlık, farkındalık.",
    image: "/images/cards/devil.jpg",
  },
  {
    id: 16,
    name: "The Tower (Yıkılan Kule)",
    arcana: "Major",
    meaningUpright: "Ani değişim, kaos, uyanış, sarsıcı gerçekler.",
    meaningReversed: "Felaketten kaçınma, korku, değişimi erteleme.",
    image: "/images/cards/tower.jpg",
  },
  {
    id: 17,
    name: "The Star (Yıldız)",
    arcana: "Major",
    meaningUpright: "Umut, inanç, yenilenme, şifa, ilham.",
    meaningReversed: "Umutsuzluk, güvensizlik, hayal kırıklığı.",
    image: "/images/cards/star.jpg",
  },
  {
    id: 18,
    name: "The Moon (Ay)",
    arcana: "Major",
    meaningUpright: "Yanılsama, korku, kaygı, rüyalar, belirsizlik.",
    meaningReversed: "Korkuların aşılması, kafa karışıklığının bitmesi.",
    image: "/images/cards/moon.jpg",
  },
  {
    id: 19,
    name: "The Sun (Güneş)",
    arcana: "Major",
    meaningUpright: "Pozitiflik, eğlence, sıcaklık, başarı, canlılık.",
    meaningReversed: "İyimserlik eksikliği, depresyon, bastırılmış neşe.",
    image: "/images/cards/sun.jpg",
  },
  {
    id: 20,
    name: "Judgement (Mahkeme)",
    arcana: "Major",
    meaningUpright: "Uyanış, muhakeme, kefaret, geçmişi değerlendirme.",
    meaningReversed: "Kendinden şüphe etme, reddediş, gecikmiş kararlar.",
    image: "/images/cards/judgement.jpg",
  },
  {
    id: 21,
    name: "The World (Dünya)",
    arcana: "Major",
    meaningUpright: "Tamamlanma, bütünleşme, başarı, seyahat.",
    meaningReversed: "Yarım kalmış işler, durgunluk, hedefe ulaşamama.",
    image: "/images/cards/world.jpg",
  },

  // === KÜÇÜK ARKANA - DEĞNEKLER (WANDS) - 14 KART ===
  {
    id: 22,
    name: "Ace of Wands",
    arcana: "Minor",
    meaningUpright: "İlham, yeni fırsat, potansiyel.",
    meaningReversed: "Gecikmeler, yaratıcılık eksikliği.",
    image: "/images/cards/wands-01.jpg",
  },
  {
    id: 23,
    name: "Two of Wands",
    arcana: "Minor",
    meaningUpright: "Planlama, gelecek kararları, keşif.",
    meaningReversed: "Korku, plansızlık, kararsızlık.",
    image: "/images/cards/wands-02.jpg",
  },
  {
    id: 24,
    name: "Three of Wands",
    arcana: "Minor",
    meaningUpright: "Genişleme, öngörü, ticaret.",
    meaningReversed: "Hayal kırıklığı, engeller.",
    image: "/images/cards/wands-03.jpg",
  },
  {
    id: 25,
    name: "Four of Wands",
    arcana: "Minor",
    meaningUpright: "Kutlama, uyum, evlilik, ev.",
    meaningReversed: "Aile içi gerginlik, istikrarsızlık.",
    image: "/images/cards/wands-04.jpg",
  },
  {
    id: 26,
    name: "Five of Wands",
    arcana: "Minor",
    meaningUpright: "Rekabet, çatışma, mücadele.",
    meaningReversed: "Çatışmadan kaçma, uzlaşma.",
    image: "/images/cards/wands-05.jpg",
  },
  {
    id: 27,
    name: "Six of Wands",
    arcana: "Minor",
    meaningUpright: "Zafer, başarı, takdir görme.",
    meaningReversed: "Başarısızlık, ego kırılması.",
    image: "/images/cards/wands-06.jpg",
  },
  {
    id: 28,
    name: "Seven of Wands",
    arcana: "Minor",
    meaningUpright: "Savunma, azim, meydan okuma.",
    meaningReversed: "Pes etmek, bunalmışlık.",
    image: "/images/cards/wands-07.jpg",
  },
  {
    id: 29,
    name: "Eight of Wands",
    arcana: "Minor",
    meaningUpright: "Hızlı hareket, seyahat, haberler.",
    meaningReversed: "Hız kesme, panik, gecikmeler.",
    image: "/images/cards/wands-08.jpg",
  },
  {
    id: 30,
    name: "Nine of Wands",
    arcana: "Minor",
    meaningUpright: "Direnç, son çaba, tetikte olma.",
    meaningReversed: "Tükenmişlik, savunmasızlık.",
    image: "/images/cards/wands-09.jpg",
  },
  {
    id: 31,
    name: "Ten of Wands",
    arcana: "Minor",
    meaningUpright: "Ağır yükler, sorumluluk, stres.",
    meaningReversed: "Yükü devretme, çöküş.",
    image: "/images/cards/wands-10.jpg",
  },
  {
    id: 32,
    name: "Page of Wands",
    arcana: "Minor",
    meaningUpright: "Coşku, keşif, yeni fikirler.",
    meaningReversed: "Hareketsizlik, kötümserlik.",
    image: "/images/cards/wands-11.jpg",
  },
  {
    id: 33,
    name: "Knight of Wands",
    arcana: "Minor",
    meaningUpright: "Enerji, tutku, macera, ferilik.",
    meaningReversed: "Öfke, düşüncesizlik, hüsran.",
    image: "/images/cards/wands-12.jpg",
  },
  {
    id: 34,
    name: "Queen of Wands",
    arcana: "Minor",
    meaningUpright: "Güven, neşe, bağımsızlık, karizma.",
    meaningReversed: "Kıskançlık, bencil olma.",
    image: "/images/cards/wands-13.jpg",
  },
  {
    id: 35,
    name: "King of Wands",
    arcana: "Minor",
    meaningUpright: "Doğal lider, vizyoner, girişimci.",
    meaningReversed: "Dürtüsellik, acımasızlık.",
    image: "/images/cards/wands-14.jpg",
  },

  // === KÜÇÜK ARKANA - KUPALAR (CUPS) - 14 KART ===
  {
    id: 36,
    name: "Ace of Cups",
    arcana: "Minor",
    meaningUpright: "Yeni aşk, duygusal uyanış, sezgi.",
    meaningReversed: "Duygusal blokaj, hayal kırıklığı.",
    image: "/images/cards/cups-01.jpg",
  },
  {
    id: 37,
    name: "Two of Cups",
    arcana: "Minor",
    meaningUpright: "Birlik, ortaklık, karşılıklı çekim.",
    meaningReversed: "Ayrılık, uyuşmazlık, güvensizlik.",
    image: "/images/cards/cups-02.jpg",
  },
  {
    id: 38,
    name: "Three of Cups",
    arcana: "Minor",
    meaningUpright: "Kutlama, arkadaşlık, topluluk.",
    meaningReversed: "Dedikodu, aşırıya kaçma.",
    image: "/images/cards/cups-03.jpg",
  },
  {
    id: 39,
    name: "Four of Cups",
    arcana: "Minor",
    meaningUpright: "Bıkkınlık, ilgisizlik, kaçırılan fırsat.",
    meaningReversed: "Farkındalık, harekete geçme.",
    image: "/images/cards/cups-04.jpg",
  },
  {
    id: 40,
    name: "Five of Cups",
    arcana: "Minor",
    meaningUpright: "Kayıp, pişmanlık, hayal kırıklığı.",
    meaningReversed: "Kabulleniş, iyileşme, umut.",
    image: "/images/cards/cups-05.jpg",
  },
  {
    id: 41,
    name: "Six of Cups",
    arcana: "Minor",
    meaningUpright: "Nostalji, çocukluk, masumiyet.",
    meaningReversed: "Geçmişe takılı kalma, büyüme.",
    image: "/images/cards/cups-06.jpg",
  },
  {
    id: 42,
    name: "Seven of Cups",
    arcana: "Minor",
    meaningUpright: "Seçenekler, hayaller, illüzyonlar.",
    meaningReversed: "Kafa netliği, karar verme.",
    image: "/images/cards/cups-07.jpg",
  },
  {
    id: 43,
    name: "Eight of Cups",
    arcana: "Minor",
    meaningUpright: "Bırakıp gitme, arayış, hayal kırıklığı.",
    meaningReversed: "Korku, kalma isteği, belirsizlik.",
    image: "/images/cards/cups-08.jpg",
  },
  {
    id: 44,
    name: "Nine of Cups",
    arcana: "Minor",
    meaningUpright: "Dileklerin gerçekleşmesi, tatmin.",
    meaningReversed: "Açgözlülük, tatminsizlik.",
    image: "/images/cards/cups-09.jpg",
  },
  {
    id: 45,
    name: "Ten of Cups",
    arcana: "Minor",
    meaningUpright: "Mutlu aile, huzur, gerçek sevgi.",
    meaningReversed: "Evde huzursuzluk, kopukluk.",
    image: "/images/cards/cups-10.jpg",
  },
  {
    id: 46,
    name: "Page of Cups",
    arcana: "Minor",
    meaningUpright: "Duygusal mesajlar, sezgi, sanat.",
    meaningReversed: "Duygusal güvensizlik, şüphe.",
    image: "/images/cards/cups-11.jpg",
  },
  {
    id: 47,
    name: "Knight of Cups",
    arcana: "Minor",
    meaningUpright: "Romantizm, cazibe, hayalperest.",
    meaningReversed: "Gerçeklerden kaçma, narsizm.",
    image: "/images/cards/cups-12.jpg",
  },
  {
    id: 48,
    name: "Queen of Cups",
    arcana: "Minor",
    meaningUpright: "Şefkat, empati, duygusal denge.",
    meaningReversed: "Aşırı hassasiyet, bağımlılık.",
    image: "/images/cards/cups-13.jpg",
  },
  {
    id: 49,
    name: "King of Cups",
    arcana: "Minor",
    meaningUpright: "Duygusal kontrol, cömertlik, bilgelik.",
    meaningReversed: "Duygusal manipülasyon, soğukluk.",
    image: "/images/cards/cups-14.jpg",
  },

  // === KÜÇÜK ARKANA - KILIÇLAR (SWORDS) - 14 KART ===
  {
    id: 50,
    name: "Ace of Swords",
    arcana: "Minor",
    meaningUpright: "Netlik, zihinsel güç, zafer.",
    meaningReversed: "Kafa karışıklığı, kaos, adaletsizlik.",
    image: "/images/cards/swords-01.jpg",
  },
  {
    id: 51,
    name: "Two of Swords",
    arcana: "Minor",
    meaningUpright: "Kararsızlık, çıkmaz sokak, denge.",
    meaningReversed: "Kararsızlığın bitmesi, bilgiye ulaşma.",
    image: "/images/cards/swords-02.jpg",
  },
  {
    id: 52,
    name: "Three of Swords",
    arcana: "Minor",
    meaningUpright: "Kalp kırıklığı, keder, ayrılık.",
    meaningReversed: "İyileşme, affetme, acının azalması.",
    image: "/images/cards/swords-03.jpg",
  },
  {
    id: 53,
    name: "Four of Swords",
    arcana: "Minor",
    meaningUpright: "Dinlenme, meditasyon, iyileşme.",
    meaningReversed: "Huzursuzluk, tükenmişlik.",
    image: "/images/cards/swords-04.jpg",
  },
  {
    id: 54,
    name: "Five of Swords",
    arcana: "Minor",
    meaningUpright: "Kazanma hırsı, çatışma, kayıplar.",
    meaningReversed: "Çatışmayı bitirme, uzlaşma.",
    image: "/images/cards/swords-05.jpg",
  },
  {
    id: 55,
    name: "Six of Swords",
    arcana: "Minor",
    meaningUpright: "Uzaklaşma, zorlukları geride bırakma.",
    meaningReversed: "Geriye dönüş, direnç, zor geçiş.",
    image: "/images/cards/swords-06.jpg",
  },
  {
    id: 56,
    name: "Seven of Swords",
    arcana: "Minor",
    meaningUpright: "Aldatılma, kaçış, strateji.",
    meaningReversed: "Gerçeğin ortaya çıkması, dürüstlük.",
    image: "/images/cards/swords-07.jpg",
  },
  {
    id: 57,
    name: "Eight of Swords",
    arcana: "Minor",
    meaningUpright: "Kısıtlanma, kurban psikolojisi.",
    meaningReversed: "Özgürleşme, yeni bakış açısı.",
    image: "/images/cards/swords-08.jpg",
  },
  {
    id: 58,
    name: "Nine of Swords",
    arcana: "Minor",
    meaningUpright: "Uykusuzluk, kabuslar, aşırı kaygı.",
    meaningReversed: "Korkularla yüzleşme, rahatlama.",
    image: "/images/cards/swords-09.jpg",
  },
  {
    id: 59,
    name: "Ten of Swords",
    arcana: "Minor",
    meaningUpright: "Yıkım, sonlanma, ihanet.",
    meaningReversed: "Yeniden doğuş, dip noktadan çıkış.",
    image: "/images/cards/swords-10.jpg",
  },
  {
    id: 60,
    name: "Page of Swords",
    arcana: "Minor",
    meaningUpright: "Meraklı, zihinsel enerji, iletişim.",
    meaningReversed: "Dedikodu, boş konuşma.",
    image: "/images/cards/swords-11.jpg",
  },
  {
    id: 61,
    name: "Knight of Swords",
    arcana: "Minor",
    meaningUpright: "Hırslı, aceleci, mantıklı.",
    meaningReversed: "Saldırganlık, sabırsızlık.",
    image: "/images/cards/swords-12.jpg",
  },
  {
    id: 62,
    name: "Queen of Swords",
    arcana: "Minor",
    meaningUpright: "Bağımsız, keskin zekalı, dürüst.",
    meaningReversed: "Zalimlik, aşırı eleştirel olma.",
    image: "/images/cards/swords-13.jpg",
  },
  {
    id: 63,
    name: "King of Swords",
    arcana: "Minor",
    meaningUpright: "Entelektüel, otorite, hakikat.",
    meaningReversed: "Güç suistimali, manipülatör.",
    image: "/images/cards/swords-14.jpg",
  },

  // === KÜÇÜK ARKANA - TILSIMLAR (PENTACLES) - 14 KART ===
  {
    id: 64,
    name: "Ace of Pentacles",
    arcana: "Minor",
    meaningUpright: "Maddi fırsat, bolluk, yeni iş.",
    meaningReversed: "Fırsat kaybı, maddi güvensizlik.",
    image: "/images/cards/pentacles-01.jpg",
  },
  {
    id: 65,
    name: "Two of Pentacles",
    arcana: "Minor",
    meaningUpright: "Dengeleme, uyum sağlama, çoklu görev.",
    meaningReversed: "Dengesizlik, plansızlık, kaos.",
    image: "/images/cards/pentacles-02.jpg",
  },
  {
    id: 66,
    name: "Three of Pentacles",
    arcana: "Minor",
    meaningUpright: "Takım çalışması, ustalık, işbirliği.",
    meaningReversed: "İşbirliği eksikliği, kötü çalışma.",
    image: "/images/cards/pentacles-03.jpg",
  },
  {
    id: 67,
    name: "Four of Pentacles",
    arcana: "Minor",
    meaningUpright: "Tutumlu olma, sahiplenme, güvenlik.",
    meaningReversed: "Açgözlülük, cimrilik, bırakamama.",
    image: "/images/cards/pentacles-04.jpg",
  },
  {
    id: 68,
    name: "Five of Pentacles",
    arcana: "Minor",
    meaningUpright: "Maddi zorluk, dışlanma, kayıp.",
    meaningReversed: "Durumun düzelmesi, iyileşme.",
    image: "/images/cards/pentacles-05.jpg",
  },
  {
    id: 69,
    name: "Six of Pentacles",
    arcana: "Minor",
    meaningUpright: "Cömertlik, paylaşım, yardım alma/verme.",
    meaningReversed: "Borçlar, eşitsizlik, bencillik.",
    image: "/images/cards/pentacles-06.jpg",
  },
  {
    id: 70,
    name: "Seven of Pentacles",
    arcana: "Minor",
    meaningUpright: "Hasat, sabır, uzun vadeli yatırım.",
    meaningReversed: "Çabaların boşa gitmesi, sabırsızlık.",
    image: "/images/cards/pentacles-07.jpg",
  },
  {
    id: 71,
    name: "Eight of Pentacles",
    arcana: "Minor",
    meaningUpright: "Çalışkanlık, gelişim, zanaat.",
    meaningReversed: "Tembellik, kalitesiz iş, odaksızlık.",
    image: "/images/cards/pentacles-08.jpg",
  },
  {
    id: 72,
    name: "Nine of Pentacles",
    arcana: "Minor",
    meaningUpright: "Lüks, bağımsızlık, maddi başarı.",
    meaningReversed: "Finansal riskler, gösteriş düşkünlüğü.",
    image: "/images/cards/pentacles-09.jpg",
  },
  {
    id: 73,
    name: "Ten of Pentacles",
    arcana: "Minor",
    meaningUpright: "Miras, aile zenginliği, uzun vadeli başarı.",
    meaningReversed: "Maddi kayıplar, ailevi kavgalar.",
    image: "/images/cards/pentacles-10.jpg",
  },
  {
    id: 74,
    name: "Page of Pentacles",
    arcana: "Minor",
    meaningUpright: "Hırs, yeni finansal hedefler, eğitim.",
    meaningReversed: "İlerleme eksikliği, tembellik.",
    image: "/images/cards/pentacles-11.jpg",
  },
  {
    id: 75,
    name: "Knight of Pentacles",
    arcana: "Minor",
    meaningUpright: "Sorumluluk, rutin, muhafazakar.",
    meaningReversed: "Sıkıcı olmak, durgunluk, inatçılık.",
    image: "/images/cards/pentacles-12.jpg",
  },
  {
    id: 76,
    name: "Queen of Pentacles",
    arcana: "Minor",
    meaningUpright: "Pratiklik, cömertlik, ev hayatı.",
    meaningReversed: "Dengesiz iş/özel hayat, kıskançlık.",
    image: "/images/cards/pentacles-13.jpg",
  },
  {
    id: 77,
    name: "King of Pentacles",
    arcana: "Minor",
    meaningUpright: "Girişimci, bolluk, güvenlik, başarı.",
    meaningReversed: "Açgözlülük, yolsuzluk, inat.",
    image: "/images/cards/pentacles-14.jpg",
  },
];
